config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'

  resources :articles
  resources :projects
  resources :communities

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  resources :communities do
    resources :community_neighbors
    resources :community_coordinators
  end

  resources :communities do
    resource :work_table
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_neighbors , dependent: :destroy
  has_many :community_coordinators , dependent: :destroy
  has_one :work_table , dependent: :destroy
end

app/models/community_coordinator.rb
class CommunityCoordinator < ApplicationRecord
  belongs_to :community
end

app/models/community_neighbor.rb
class CommunityNeighbor < ApplicationRecord
  belongs_to :community
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/work_table.rb
class WorkTable < ApplicationRecord
  belongs_to :community
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
    end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end

  def show
    @community = Community.find(params[:id])
  end

  def new
    @community = Community.new
  end

  def edit
    @community = Community.find(params[:id])
  end

  def create
    @community = Community.new(community_params)

    if @community.save
      redirect_to @community
    else
      render 'new'
    end
  end

  def update
    @community = Community.find(params[:id])

    if @community.update(community_params)
      redirect_to @community
    else
      render 'edit'
    end
  end

  def destroy
    @community = Community.find(params[:id])
    @community.destroy

    redirect_to communities_path
  end

  private
  def community_params
    params.require(:community).permit(:country, :province_region, :municipality_location, :community_name, :community_status)
  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :project_type, :project_subtype, :financing, :project_start, :project_situation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_tables_helper.rb
module WorkTablesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
f
<%= form_with(model: [ @article, @article.comments.build ]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/communities/_form.html.erb
<%= form_with model: @community, local: true do |form| %>

  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@community.errors.count, "error") %> prohibited
        this community from being saved:
      </h2>
      <ul>
        <% @community.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :'País de la comunidad' %><br>
    <%= form.text_field :country %>
  </p>

  <p>
    <%= form.label :'Departamento/Provincia/Región' %><br>
    <%= form.text_field :province_region %>
  </p>

  <p>
    <%= form.label :'Municipalidad/Comuna/Localidad' %><br>
    <%= form.text_field :municipality_location %>
  </p>

  <p>
    <%= form.label :'Nombre de la comunidad:' %><br>
    <%= form.text_field :community_name %>
  </p>
  <p>
    <%= form.label :'Estado de la comunidad:' %><br>
    <%= form.text_field :community_status %>
  </p>

  <p>
    <%= form.submit "Enviar datos"%>
  </p>

<% end %>

app/views/communities/edit.html.erb
<h1>Editar comunidad</h1>
<%= render 'form' %>

app/views/communities/index.html.erb
<h1>Listado de Comunidades</h1>
<table>
  <tr>
    <th><h2>Nombre</h2></th>
    <th><h2>País</h2></th>
    <th><h2>Región</h2></th>
    <th><h2>Comuna</h2></th>
    <th><h2>Estado</h2></th>
    <th colspan="3"></th>
  </tr>

  <% @communities.each do |community| %>
    <tr>
      <th><%= link_to community.community_name, community_path(community) %></th>
      <th><%= community.country%></th>
      <th><%= community.province_region%></th>
      <th><%= community.municipality_location%></th>
      <th><%= community.community_status%></th>
      <td><%= link_to 'Borrar', community_path(community),
              method: :delete,
              data: { confirm: '¿Estás seguro?' }%></td>
    </tr>
  <% end %>
</table>
<td><%= link_to 'Nuevo', new_community_path(@community) %></td>

app/views/communities/new.html.erb
<h1>Nuevo comunidad</h1>
<%= render 'form' %>

app/views/communities/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @community.community_name %>
</p>

<p>
  <strong>País:</strong>
  <%= @community.country %>
</p>

<p>
  <strong>Region:</strong>
  <%= @community.province_region %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @community.municipality_location %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @community.community_status  %>
</p>
<td><%= link_to 'Editar', edit_community_path(@community) %></td>
<td><%= link_to 'Borrar', community_path(@community),
        method: :delete, data: { confirm: "¿Estás seguro de borrar?"}%></td>
<td><%= link_to 'Volver', communities_path %></td>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Teléfono</th>
    <th>E-Mail</th>
    <th>Estado</th>
    <th colspan="4"></th>
  </tr>
<h2>Vecinos de la comunidad</h2>

<% @community.community_neighbors.each do |community_neighbor| %>
<tr>
    <th><%= community_neighbor.name %></th>
    <th><%= community_neighbor.surname %></th>
    <th><%= community_neighbor.phone %></th>
    <th><%= community_neighbor.mail %></th>
    <th><%= community_neighbor.status %></th>


<th><th><%= link_to 'Editar vecino', edit_community_community_neighbor_path(@community, community_neighbor) %><th>
</tr>
<% end %>
</table>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Teléfono</th>
    <th>E-Mail</th>
    <th>Estado</th>
    <th>Fecha de inicio</th>
    <th>Fecha de fin</th>
    <th colspan="4"></th>
  </tr>
<%= link_to 'Nuevo vecino', new_community_community_neighbor_url(@community) %>

<h2>Coordinadores de la comunidad</h2>
<% @community.community_coordinators.each do |community_coordinator| %>
<tr>
    <th><%= community_coordinator.name %></th>
    <th><%= community_coordinator.surname %></th>
    <th><%= community_coordinator.phone %></th>
    <th><%= community_coordinator.mail %></th>
    <th><%= community_coordinator.status %></th>
    <th><%= community_coordinator.start_date %></th>
    <th><%= community_coordinator.end_date %></th>


<th><th><%= link_to 'Editar vecino', edit_community_community_coordinator_path(@community, community_coordinator) %><th>
</tr>
<% end %>
</table>
<%= link_to 'Nuevo coordinador', new_community_community_coordinator_url(@community) %>

app/views/projects/index.html.erb
<h1>Listado de proyectos</h1>
<table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Tipo</th>
    <th>Subtipo</th>
    <th colspan="3"></th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <th><%= link_to project.name, project_path(project) %></th>
      <th><%= project.description %></th>
      <th><%= project.project_type %></th>
      <th><%= project.project_subtype %></th>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>Nuevo proyecto</h1>

<%= form_with scope: :project, url: projects_path, local: true do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :'nombre proyecto' %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :"Descripción" %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :"Tipo" %><br>
    <%= form.select(:project_type, (['Vivienda', 'Necesidades básicas'])) %>
  </p>

  <p>
    <%= form.label :"Subtipo" %><br>
    <%= form.select(:project_subtype, (['Subnecesidad 1', 'Subnecesidad 2'])) %>
  </p>

  <p>
    <%= form.label :"Financiamiento" %><br>
    <%= form.select(:financing, (['Financiamiento 1', 'Financiamiento 2'])) %>
  </p>

  <p>
    <%= form.label :"Fecha de inicio" %><br>
    <%= form.date_select :project_start %>

    <!-- <%= form.date_select :project_start %> -->


  </p>


  <p>
    <%= form.submit "Crear proyecto" %>
  </p>

<% end %>

app/views/projects/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @project.name %><br/>
  <strong>Descripción:</strong>
  <%= @project.description %><br/>
  <strong>Tipo:</strong>
  <%= @project.project_type %><br/>
  <strong>Subtipo:</strong>
  <%= @project.project_subtype %><br/>
  <strong>Financiamiento:</strong>
  <%= @project.financing %><br/>
  <strong>Situación del proyecto:</strong>
  <%= @project.project_situation %><br/>
  <strong>Fecha de inicio:</strong>
  <%= @project.project_start %><br/>
  <strong>Fecha de fin:</strong>
  <%= @project.project_end %><br/>
  <td><%= link_to 'Borrar', project_path(@project),
          method: :delete,
          data: { confirm: '¿Está seguro que desea borrar el proyecto?' }%></td>
</p>